[global]
strategy = 'all'
filter = false
log_level = 'debug'
clear_packets_interval = 100
tx_confirmation = true

[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'earth'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'http://127.0.0.1:9095'
websocket_addr = 'ws://127.0.0.1:26657/websocket'
account_prefix = 'cosmos'
address_type = { derivation = 'cosmos' }
key_name = 'alice'
store_prefix = 'ibc'
max_gas = 3000000
gas_price = { price = 0.001, denom = 'stake' }
gas_adjustment = 0.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }


[[chains]]
id = 'mars'
rpc_addr = 'http://127.0.0.1:26658'
grpc_addr = 'http://127.0.0.1:9097'
websocket_addr = 'ws://127.0.0.1:26658/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
address_type = { derivation = 'cosmos' }
key_name = 'bob'
store_prefix = 'ibc'
max_gas = 3000000
gas_price = { price = 0.001, denom = 'stake' }
gas_adjustment = 0.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'ibc-0'
rpc_addr = 'http://127.0.0.1:9944'
grpc_addr = 'http://127.0.0.1:9090'
websocket_addr = 'ws://127.0.0.1:9944/websocket'
rpc_timeout = '10s'
account_prefix = 'substrate'
key_name = 'testkey'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
max_gas = 3000000
gas_price = { price = 0.001, denom = 'stake' }
gas_adjustment = 0.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }


[[chains]]
id = 'ibc-1'
rpc_addr = 'http://127.0.0.1:8844'
grpc_addr = 'http://127.0.0.1:9091'
# subscribe subtstrate client
websocket_addr = 'ws://127.0.0.1:8844/websocket'
rpc_timeout = '10s'
account_prefix = 'substrate'
key_name = 'testkey'
store_prefix = 'ibc'
max_gas = 3000000
gas_price = { price = 0.001, denom = 'stake' }
gas_adjustment = 0.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
